### ISSUE TITLE
Uncommented SOC line in basic rules.rb --- Error in log

### ISSUE THREAD

**Issue by emtemt** [celsworth/octolux#4]
Uncommented this line to log SOC.

#LOGGER.info "Battery SOC = #{ls.data['soc']}%" if ls.inputs['soc']

This was the result in the log:

rules.rb:15:in `<main>': undefined method `data' for #<LuxStatus:0x016ab458> (NoMethodError)
	from /home/pi/octolux/octolux.rb:30:in `instance_eval'
	from /home/pi/octolux/octolux.rb:30:in `<main>'
I, [2020-05-26T11:00:04.005927 #7152]  INFO -- : Current Octopus Unit Price: 6.279p
rules.rb:15:in `<main>': undefined method `data' for #<LuxStatus:0x01bbce20> (NoMethodError)
	from /home/pi/octolux/octolux.rb:30:in `instance_eval'
	from /home/pi/octolux/octolux.rb:30:in `<main>'
I, [2020-05-26T11:00:21.233267 #7161]  INFO -- : Current Octopus Unit Price: 6.279p
rules.rb:15:in `<main>': undefined method `data' for #<LuxStatus:0x025fe528> (NoMethodError)
	from /home/pi/octolux/octolux.rb:30:in `instance_eval'
	from /home/pi/octolux/octolux.rb:30:in `<main>'
I, [2020-05-26T11:00:38.435472 #7167]  INFO -- : Current Octopus Unit Price: 6.279p

**Comment by John-Glasson** [comment]
I just came across this (2 years later!) having had the same issue. I discover that 'ls.data['soc'] should be ls.input['soc'].
